import type { SymbolDefinition } from '@/types/symbol'

export const crochetSymbols: SymbolDefinition[] = [
  {
    id: 'ch',
    name: '사슬뜨기',
    nameEn: 'chain',
    abbreviation: 'ch',
    category: 'crochet',
    svgPath: 'M 5,15 A 10,10 0 1,1 25,15 A 10,10 0 1,1 5,15 Z',
    width: 1,
    height: 1,
  },
  {
    id: 'sc',
    name: '짧은뜨기',
    nameEn: 'single crochet',
    abbreviation: 'sc',
    category: 'crochet',
    svgPath: 'M 5,25 L 15,5 L 25,25 M 8,18 L 22,18',
    width: 1,
    height: 1,
  },
  {
    id: 'hdc',
    name: '중장편뜨기',
    nameEn: 'half double crochet',
    abbreviation: 'hdc',
    category: 'crochet',
    svgPath: 'M 15,25 L 15,5 M 8,12 L 22,12',
    width: 1,
    height: 1,
  },
  {
    id: 'dc',
    name: '긴뜨기',
    nameEn: 'double crochet',
    abbreviation: 'dc',
    category: 'crochet',
    svgPath: 'M 15,25 L 15,3 M 8,10 L 22,10 M 10,17 L 20,17',
    width: 1,
    height: 2,
  },
  {
    id: 'tr',
    name: '한길긴뜨기',
    nameEn: 'treble crochet',
    abbreviation: 'tr',
    category: 'crochet',
    svgPath: 'M 15,25 L 15,3 M 8,8 L 22,8 M 8,14 L 22,14 M 8,20 L 22,20',
    width: 1,
    height: 2,
  },
  {
    id: 'sl_st',
    name: '빼뜨기',
    nameEn: 'slip stitch',
    abbreviation: 'sl st',
    category: 'crochet',
    svgPath: 'M 12,15 A 3,3 0 1,1 18,15 A 3,3 0 1,1 12,15 Z',
    width: 1,
    height: 1,
  },
  {
    id: 'inc',
    name: '늘림코',
    nameEn: 'increase',
    abbreviation: 'inc',
    category: 'crochet',
    svgPath: 'M 5,25 L 15,5 L 25,25',
    width: 1,
    height: 1,
  },
  {
    id: 'dec',
    name: '줄임코',
    nameEn: 'decrease',
    abbreviation: 'dec',
    category: 'crochet',
    svgPath: 'M 5,5 L 15,25 L 25,5',
    width: 1,
    height: 1,
  },
]
