import type { SymbolDefinition } from '@/types/symbol'

export const knittingSymbols: SymbolDefinition[] = [
  {
    id: 'k',
    name: '겉뜨기',
    nameEn: 'knit',
    abbreviation: 'k',
    category: 'knitting',
    svgPath: 'M 15,5 L 15,25',
    width: 1,
    height: 1,
  },
  {
    id: 'p',
    name: '안뜨기',
    nameEn: 'purl',
    abbreviation: 'p',
    category: 'knitting',
    svgPath: 'M 5,15 L 25,15',
    width: 1,
    height: 1,
  },
  {
    id: 'yo',
    name: '감아뜨기',
    nameEn: 'yarn over',
    abbreviation: 'yo',
    category: 'knitting',
    svgPath: 'M 5,15 A 10,10 0 1,1 25,15 A 10,10 0 1,1 5,15 Z',
    width: 1,
    height: 1,
  },
  {
    id: 'k2tog',
    name: '오른코 모아뜨기',
    nameEn: 'knit 2 together',
    abbreviation: 'k2tog',
    category: 'knitting',
    svgPath: 'M 5,25 L 25,5',
    width: 1,
    height: 1,
  },
  {
    id: 'ssk',
    name: '왼코 모아뜨기',
    nameEn: 'slip slip knit',
    abbreviation: 'ssk',
    category: 'knitting',
    svgPath: 'M 5,5 L 25,25',
    width: 1,
    height: 1,
  },
]
