import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import type { WrittenRow } from '@/lib/written/converter'

export async function exportToPdf(
  canvasElement: HTMLElement,
  writtenRows: WrittenRow[],
  title: string
): Promise<void> {
  const canvas = await html2canvas(canvasElement, {
    scale: 2,
    backgroundColor: '#ffffff',
    logging: false,
  })
  const imgData = canvas.toDataURL('image/png')

  const pdf = new jsPDF('p', 'mm', 'a4')
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()

  // 헤더
  pdf.setFontSize(16)
  pdf.text(title, pageWidth / 2, 15, { align: 'center' })
  pdf.setFontSize(8)
  pdf.setTextColor(150)
  pdf.text(`Generated by KnitCanvas - ${new Date().toLocaleDateString('ko')}`, pageWidth / 2, 21, {
    align: 'center',
  })
  pdf.setTextColor(0)

  // 1페이지: 차트 이미지
  const imgWidth = pageWidth - 20
  const imgHeight = (canvas.height * imgWidth) / canvas.width
  const maxImgHeight = pageHeight - 35

  if (imgHeight > maxImgHeight) {
    // 이미지가 너무 크면 축소
    const scale = maxImgHeight / imgHeight
    const scaledWidth = imgWidth * scale
    const scaledHeight = imgHeight * scale
    pdf.addImage(
      imgData,
      'PNG',
      (pageWidth - scaledWidth) / 2,
      28,
      scaledWidth,
      scaledHeight
    )
  } else {
    pdf.addImage(imgData, 'PNG', 10, 28, imgWidth, imgHeight)
  }

  // 2페이지: 서술형 텍스트
  if (writtenRows.length > 0) {
    pdf.addPage()
    pdf.setFontSize(14)
    pdf.text('Written Pattern', pageWidth / 2, 15, { align: 'center' })

    pdf.setFontSize(10)
    let y = 28
    for (const row of writtenRows) {
      const line = `Row ${row.rowNumber}: ${row.instructions}`
      pdf.text(line, 10, y)
      y += 6
      if (y > pageHeight - 15) {
        pdf.addPage()
        y = 15
      }
    }
  }

  pdf.save(`${title}.pdf`)
}
