import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import type { WrittenRow } from '@/lib/written/converter'

function addWatermarkToPage(pdf: jsPDF, watermark: string) {
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  pdf.saveGraphicsState()
  pdf.setTextColor(200, 200, 200)
  pdf.setFontSize(14)
  // Draw diagonal watermark text in a grid pattern
  const step = 45
  for (let y = 0; y < pageHeight + step; y += step) {
    for (let x = 0; x < pageWidth + step; x += step) {
      pdf.text(watermark, x, y, { angle: 45 })
    }
  }
  pdf.restoreGraphicsState()
  pdf.setTextColor(0)
}

export async function exportToPdf(
  canvasElement: HTMLElement,
  writtenRows: WrittenRow[],
  title: string,
  watermark?: string
): Promise<void> {
  const canvas = await html2canvas(canvasElement, {
    scale: 2,
    backgroundColor: '#ffffff',
    logging: false,
  })
  const imgData = canvas.toDataURL('image/png')

  const pdf = new jsPDF('p', 'mm', 'a4')
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()

  // PDF metadata (for leak tracking when watermark is set)
  pdf.setProperties({
    title,
    creator: 'KnitCanvas',
    subject: watermark ? `Licensed to: ${watermark}` : '',
    keywords: watermark ? `buyer:${watermark}` : '',
  })

  // 헤더
  pdf.setFontSize(16)
  pdf.text(title, pageWidth / 2, 15, { align: 'center' })
  pdf.setFontSize(8)
  pdf.setTextColor(150)
  pdf.text(`Generated by KnitCanvas - ${new Date().toLocaleDateString('ko')}`, pageWidth / 2, 21, {
    align: 'center',
  })
  pdf.setTextColor(0)

  // 1페이지: 차트 이미지
  const imgWidth = pageWidth - 20
  const imgHeight = (canvas.height * imgWidth) / canvas.width
  const maxImgHeight = pageHeight - 35

  if (imgHeight > maxImgHeight) {
    // 이미지가 너무 크면 축소
    const scale = maxImgHeight / imgHeight
    const scaledWidth = imgWidth * scale
    const scaledHeight = imgHeight * scale
    pdf.addImage(
      imgData,
      'PNG',
      (pageWidth - scaledWidth) / 2,
      28,
      scaledWidth,
      scaledHeight
    )
  } else {
    pdf.addImage(imgData, 'PNG', 10, 28, imgWidth, imgHeight)
  }

  if (watermark) addWatermarkToPage(pdf, watermark)

  // 2페이지: 서술형 텍스트
  if (writtenRows.length > 0) {
    pdf.addPage()
    pdf.setFontSize(14)
    pdf.text('Written Pattern', pageWidth / 2, 15, { align: 'center' })

    pdf.setFontSize(10)
    let y = 28
    for (const row of writtenRows) {
      const line = `Row ${row.rowNumber}: ${row.instructions}`
      pdf.text(line, 10, y)
      y += 6
      if (y > pageHeight - 15) {
        pdf.addPage()
        y = 15
        if (watermark) addWatermarkToPage(pdf, watermark)
      }
    }
    if (watermark) addWatermarkToPage(pdf, watermark)
  }

  pdf.save(`${title}.pdf`)
}
